spring:
  application:
    name: ${PROJECT_NAME:order-management}
  web:
    servlet:
      context-path: ${CONTEXT_PATH:/api/v1}

  server:
    port: ${SERVER_PORT:8080}
    profiles:
      active: local

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml

  datasource:
    url: jdbc:postgresql://localhost:5432/order-management
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: orderManagementPool
      maximum-pool-size: 10
      minimum-idle: 2

#  datasource:
#    url: jdbc:postgresql://localhost:5432/order-management
#    username: ${SPRING_DATASOURCE_USERNAME:postgres}
#    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
#    driver-class-name: org.postgresql.Driver
#    hikari:
#      pool-name: orderManagementPool
#      maximum-pool-size: ${SPRING_DATASOURCE_MAX_POOL_SIZE:10}
#      minimum-idle: ${SPRING_DATASOURCE_MIN_IDLE:2}

  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    timeout: ${REDIS_TIMEOUT:5000}
    lettuce:
      pool:
        max-active: ${REDIS_MAX_ACTIVE:8}
        max-idle: ${REDIS_MAX_IDLE:8}
        min-idle: ${REDIS_MIN_IDLE:2}

  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: ${SPRING_JPA_SHOW_SQL:true} # Habilitar apenas em dev

  security:
    oauth2:
      client:
        registration:
          default:
            client-id: ${OAUTH_CLIENT_ID:xpto-id}
            client-secret: ${OAUTH_CLIENT_SECRET:xpto-secret}
            scope: ${OAUTH_CLIENT_SCOPE:read,write}
        provider:
          default:
            token-uri: ${OAUTH_TOKEN_URI:http://oauth-provider/token}
            authorization-uri: ${OAUTH_AUTHORIZATION_URI:http://oauth-provider/authorize}

logging:
  level:
    root: ${LOGGING_LEVEL_ROOT:INFO}
    com.lutrapp: ${LOGGING_LEVEL_PROJECT:DEBUG}
  file:
    name: ${LOGGING_FILE_NAME:logs/app.log}
